name: CI for macOS
# https://github.com/google/mozc/blob/master/docs/build_mozc_in_osx.md

# Run on push.
on: push

# Prevent previous workflows from running.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    runs-on: macos-11
    timeout-minutes: 90

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: '3.9'

      - name: Install pip dependencies
        working-directory: ./src
        run: |
          python3 -m pip install six requests

      - name: Install dependencies
        working-directory: ./src
        run: |
          python3 build_tools/update_deps.py

      - name: Build Qt
        working-directory: ./src
        run: |
          python3 build_tools/build_qt.py --release --confirm_license
          echo "MOZC_QT_PATH=${PWD}/third_party/qt" >> $GITHUB_ENV

      - name: bazel build
        working-directory: ./src
        run: |
          bazel build --config oss_macos package

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Mozc.pkg
          path: src/bazel-bin/mac/Mozc.pkg
          if-no-files-found: warn

  test:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    runs-on: macos-11
    timeout-minutes: 90

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: '3.9'

      - name: Install pip dependencies
        working-directory: ./src
        run: |
          python3 -m pip install six requests

      - name: Install dependencies
        working-directory: ./src
        run: |
          python3 build_tools/update_deps.py

      - name: Build Qt
        working-directory: ./src
        run: |
          python3 build_tools/build_qt.py --release --confirm_license
          echo "MOZC_QT_PATH=${PWD}/third_party/qt" >> $GITHUB_ENV

      - name: bazel test
        working-directory: ./src
        run: |
          bazel test ... --config oss_macos --build_tests_only -- -session:session_watch_dog_test
